version: '2'
services:
  knotification-app:
    image: knotification
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATA_MONGODB_URI=mongodb://knotification-mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=knotification
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
  knotification-mongodb:
    extends:
      file: mongodb.yml
      service: knotification-mongodb
